<?php

namespace Database\Seeders;

use App\Models\Driver;
use Illuminate\Database\Seeder;

class DriverSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $drivers = [
            [
                'name' => 'Michael Johnson',
                'email' => 'michael.johnson@citylink.com',
                'phone' => '+1 (555) 123-4567',
                'date_of_birth' => '1985-03-15',
                'bio' => 'Experienced professional driver with 12 years of service. Specializes in luxury and executive transport.',
                'license_number' => 'DL1234567890',
                'license_expiry' => '2026-12-31',
                'experience_years' => 12,
                'languages' => ['English', 'Spanish'],
                'status' => 'active',
                'verification_status' => 'verified',
                'is_available' => true,
                'background_check_status' => 'passed',
                'rating_avg' => 4.8,
                'total_trips' => 450,
                'total_earnings' => 45000.00,
                'acceptance_rate' => 95.50,
                'cancellation_rate' => 1.20,
                'approved_at' => now()->subDays(30),
                'approved_by' => 1,
            ],
            [
                'name' => 'Sarah Williams',
                'email' => 'sarah.williams@citylink.com',
                'phone' => '+1 (555) 234-5678',
                'date_of_birth' => '1990-07-22',
                'bio' => 'Friendly and reliable driver with excellent customer service skills. Perfect for airport transfers.',
                'license_number' => 'DL2345678901',
                'license_expiry' => '2027-06-30',
                'experience_years' => 8,
                'languages' => ['English', 'French'],
                'status' => 'active',
                'verification_status' => 'verified',
                'is_available' => true,
                'background_check_status' => 'passed',
                'rating_avg' => 4.9,
                'total_trips' => 320,
                'total_earnings' => 32000.00,
                'acceptance_rate' => 98.00,
                'cancellation_rate' => 0.80,
                'approved_at' => now()->subDays(45),
                'approved_by' => 1,
            ],
            [
                'name' => 'David Martinez',
                'email' => 'david.martinez@citylink.com',
                'phone' => '+1 (555) 345-6789',
                'date_of_birth' => '1988-11-10',
                'bio' => 'Safe and professional driver with a clean driving record. Specializes in business travel.',
                'license_number' => 'DL3456789012',
                'license_expiry' => '2026-09-15',
                'experience_years' => 10,
                'languages' => ['English', 'Spanish', 'Portuguese'],
                'status' => 'active',
                'verification_status' => 'verified',
                'is_available' => false,
                'background_check_status' => 'passed',
                'rating_avg' => 4.7,
                'total_trips' => 280,
                'total_earnings' => 28000.00,
                'acceptance_rate' => 92.00,
                'cancellation_rate' => 2.10,
                'approved_at' => now()->subDays(60),
                'approved_by' => 1,
            ],
            [
                'name' => 'Emily Chen',
                'email' => 'emily.chen@citylink.com',
                'phone' => '+1 (555) 456-7890',
                'date_of_birth' => '1992-05-08',
                'bio' => 'Bilingual driver with excellent navigation skills. Great for city tours and sightseeing.',
                'license_number' => 'DL4567890123',
                'license_expiry' => '2027-03-20',
                'experience_years' => 6,
                'languages' => ['English', 'Chinese'],
                'status' => 'active',
                'verification_status' => 'verified',
                'is_available' => true,
                'background_check_status' => 'passed',
                'rating_avg' => 4.95,
                'total_trips' => 195,
                'total_earnings' => 19500.00,
                'acceptance_rate' => 99.00,
                'cancellation_rate' => 0.50,
                'approved_at' => now()->subDays(20),
                'approved_by' => 1,
            ],
            [
                'name' => 'James Anderson',
                'email' => 'james.anderson@citylink.com',
                'phone' => '+1 (555) 567-8901',
                'date_of_birth' => '1983-09-25',
                'bio' => 'Veteran driver with extensive knowledge of the area. Reliable and punctual.',
                'license_number' => 'DL5678901234',
                'license_expiry' => '2026-11-10',
                'experience_years' => 15,
                'languages' => ['English'],
                'status' => 'active',
                'verification_status' => 'verified',
                'is_available' => true,
                'background_check_status' => 'passed',
                'rating_avg' => 4.6,
                'total_trips' => 500,
                'total_earnings' => 50000.00,
                'acceptance_rate' => 90.00,
                'cancellation_rate' => 2.50,
                'approved_at' => now()->subDays(90),
                'approved_by' => 1,
            ],
            [
                'name' => 'Lisa Thompson',
                'email' => 'lisa.thompson@citylink.com',
                'phone' => '+1 (555) 678-9012',
                'date_of_birth' => '1995-01-12',
                'bio' => 'Young and energetic driver with a passion for excellent service.',
                'license_number' => 'DL6789012345',
                'license_expiry' => '2027-08-15',
                'experience_years' => 4,
                'languages' => ['English', 'German'],
                'status' => 'active',
                'verification_status' => 'pending',
                'is_available' => false,
                'background_check_status' => 'pending',
                'rating_avg' => 4.5,
                'total_trips' => 120,
                'total_earnings' => 12000.00,
                'acceptance_rate' => 88.00,
                'cancellation_rate' => 3.00,
                'approved_at' => null,
                'approved_by' => null,
            ],
            [
                'name' => 'Robert Garcia',
                'email' => 'robert.garcia@citylink.com',
                'phone' => '+1 (555) 789-0123',
                'date_of_birth' => '1987-06-30',
                'bio' => 'Professional driver with focus on safety and comfort.',
                'license_number' => 'DL7890123456',
                'license_expiry' => '2026-10-25',
                'experience_years' => 9,
                'languages' => ['English', 'Spanish'],
                'status' => 'inactive',
                'verification_status' => 'verified',
                'is_available' => false,
                'background_check_status' => 'passed',
                'rating_avg' => 4.4,
                'total_trips' => 180,
                'total_earnings' => 18000.00,
                'acceptance_rate' => 85.00,
                'cancellation_rate' => 4.00,
                'approved_at' => now()->subDays(120),
                'approved_by' => 1,
            ],
            [
                'name' => 'Jennifer Lee',
                'email' => 'jennifer.lee@citylink.com',
                'phone' => '+1 (555) 890-1234',
                'date_of_birth' => '1991-12-05',
                'bio' => 'Courteous and professional driver specializing in VIP transport.',
                'license_number' => 'DL8901234567',
                'license_expiry' => '2027-05-10',
                'experience_years' => 7,
                'languages' => ['English', 'Arabic'],
                'status' => 'active',
                'verification_status' => 'verified',
                'is_available' => true,
                'background_check_status' => 'passed',
                'rating_avg' => 4.85,
                'total_trips' => 240,
                'total_earnings' => 24000.00,
                'acceptance_rate' => 96.50,
                'cancellation_rate' => 1.00,
                'approved_at' => now()->subDays(50),
                'approved_by' => 1,
            ],
            [
                'name' => 'Thomas Wilson',
                'email' => 'thomas.wilson@citylink.com',
                'phone' => '+1 (555) 901-2345',
                'date_of_birth' => '1984-04-18',
                'bio' => 'Experienced driver with strong customer relations and local expertise.',
                'license_number' => 'DL9012345678',
                'license_expiry' => '2026-07-22',
                'experience_years' => 11,
                'languages' => ['English', 'Hindi'],
                'status' => 'active',
                'verification_status' => 'verified',
                'is_available' => true,
                'background_check_status' => 'passed',
                'rating_avg' => 4.75,
                'total_trips' => 380,
                'total_earnings' => 38000.00,
                'acceptance_rate' => 93.00,
                'cancellation_rate' => 1.80,
                'approved_at' => now()->subDays(70),
                'approved_by' => 1,
            ],
            [
                'name' => 'Amanda Rodriguez',
                'email' => 'amanda.rodriguez@citylink.com',
                'phone' => '+1 (555) 012-3456',
                'date_of_birth' => '1993-08-14',
                'bio' => 'Friendly driver with attention to detail and passenger comfort.',
                'license_number' => 'DL0123456789',
                'license_expiry' => '2027-12-05',
                'experience_years' => 5,
                'languages' => ['English', 'Spanish', 'French'],
                'status' => 'active',
                'verification_status' => 'pending',
                'is_available' => false,
                'background_check_status' => 'pending',
                'rating_avg' => 4.65,
                'total_trips' => 150,
                'total_earnings' => 15000.00,
                'acceptance_rate' => 89.00,
                'cancellation_rate' => 2.80,
                'approved_at' => null,
                'approved_by' => null,
            ],
        ];

        foreach ($drivers as $driverData) {
            Driver::create($driverData);
        }
    }
}
