<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Package;
use Illuminate\Support\Str;

class PackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $packages = [
            // Airport Packages
            [
                'name' => 'Airport Transfer - Standard',
                'slug' => 'airport-transfer-standard',
                'category' => 'airport',
                'short_description' => 'Reliable airport pickup and drop-off service',
                'description' => 'Experience stress-free airport transfers with our premium chauffeur service. Our professional drivers ensure punctual pickups, comfortable rides, and seamless drop-offs at all major airports.',
                'duration_hours' => 1,
                'passenger_capacity' => 3,
                'luggage_capacity' => 3,
                'base_price' => 49.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'min_booking_hours' => 1,
                'availability_24_7' => true,
                'inclusions' => ['Professional uniformed chauffeur', 'Luxury vehicle with WiFi', 'Meet & greet service', 'Flight tracking & monitoring', 'Bottled water & refreshments', '24/7 customer support'],
                'exclusions' => ['Gratuity (suggested 15-20%)', 'Parking fees at destination', 'Additional stops'],
                'quick_facts' => ['vehicle' => 'Luxury Sedan', 'availability' => '24/7'],
                'terms_conditions' => 'Minimum 24-hour advance booking required. Cancellations accepted up to 4 hours before pickup. Additional charges apply for wait time beyond 15 minutes.',
                'cancellation_policy' => 'Free cancellation up to 4 hours before scheduled pickup time. Cancellations within 4 hours subject to 50% charge.',
                'meta_title' => 'Airport Transfer Service - Professional Chauffeur',
                'meta_description' => 'Book reliable airport transfer service with professional chauffeurs, luxury vehicles, and 24/7 availability.',
            ],
            [
                'name' => 'Airport Transfer - Premium',
                'slug' => 'airport-transfer-premium',
                'category' => 'airport',
                'short_description' => 'Luxury airport service with extended waiting time',
                'description' => 'Premium airport transfer service featuring luxury vehicles, priority service, and complimentary waiting time. Perfect for business travelers and VIP guests.',
                'duration_hours' => 1,
                'passenger_capacity' => 4,
                'luggage_capacity' => 4,
                'base_price' => 79.00,
                'discount_percentage' => 10.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'min_booking_hours' => 1,
                'availability_24_7' => true,
                'inclusions' => ['Professional uniformed chauffeur', 'Luxury executive vehicle', 'Meet & greet with name board', 'Flight tracking', 'Complimentary refreshments', '30-minute free waiting time', 'Priority service'],
                'exclusions' => ['Gratuity', 'Additional stops'],
                'quick_facts' => ['vehicle' => 'Executive Sedan', 'availability' => '24/7'],
                'terms_conditions' => 'Minimum 12-hour advance booking required. Free cancellation up to 2 hours before pickup.',
                'cancellation_policy' => 'Free cancellation up to 2 hours before pickup. Late cancellations subject to 30% charge.',
                'meta_title' => 'Premium Airport Transfer - VIP Service',
                'meta_description' => 'Experience luxury airport transfers with executive vehicles and VIP service.',
            ],
            [
                'name' => 'Airport Group Transfer',
                'slug' => 'airport-group-transfer',
                'category' => 'airport',
                'short_description' => 'Spacious airport transfer for groups and families',
                'description' => 'Comfortable airport transfers for larger groups. Our spacious vehicles accommodate up to 8 passengers with ample luggage space.',
                'duration_hours' => 2,
                'passenger_capacity' => 8,
                'luggage_capacity' => 8,
                'base_price' => 99.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
                'min_booking_hours' => 1,
                'availability_24_7' => true,
                'inclusions' => ['Professional chauffeur', 'Luxury SUV or van', 'Meet & greet', 'Flight tracking', 'Refreshments', '24/7 support'],
                'exclusions' => ['Gratuity', 'Child seats (available on request)'],
                'quick_facts' => ['vehicle' => 'Luxury SUV/Van', 'availability' => '24/7'],
                'terms_conditions' => 'Minimum 24-hour advance booking required for group transfers.',
                'cancellation_policy' => 'Free cancellation up to 6 hours before pickup.',
                'meta_title' => 'Group Airport Transfer Service',
                'meta_description' => 'Spacious airport transfers for groups up to 8 passengers.',
            ],
            
            // Wedding Packages
            [
                'name' => 'Wedding Chauffeur - Classic',
                'slug' => 'wedding-chauffeur-classic',
                'category' => 'wedding',
                'short_description' => 'Elegant transportation for your special day',
                'description' => 'Arrive in style for your big day with our luxury wedding chauffeur service. Professional service and immaculate vehicles to make your wedding day memorable.',
                'duration_hours' => 4,
                'passenger_capacity' => 6,
                'luggage_capacity' => 2,
                'base_price' => 199.00,
                'discount_price' => 179.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
                'min_booking_hours' => 4,
                'availability_24_7' => false,
                'inclusions' => ['Professional chauffeur', 'Luxury wedding vehicle', 'Red carpet service', 'Champagne service', 'Vehicle decoration', 'Professional photos', 'Flexible timing'],
                'exclusions' => ['Additional hours (available at $50/hour)', 'Multiple venue stops'],
                'quick_facts' => ['vehicle' => 'Luxury Wedding Car', 'availability' => 'By appointment'],
                'terms_conditions' => 'Minimum 2-week advance booking required. Full payment due 7 days before event.',
                'cancellation_policy' => 'Free cancellation up to 14 days before event. 50% refund for 7-14 days notice.',
                'meta_title' => 'Wedding Chauffeur Service - Classic Package',
                'meta_description' => 'Elegant wedding transportation with luxury vehicles and professional service.',
            ],
            [
                'name' => 'Wedding Chauffeur - Luxury',
                'slug' => 'wedding-chauffeur-luxury',
                'category' => 'wedding',
                'short_description' => 'Premium wedding transportation with extended service',
                'description' => 'Our luxury wedding package provides comprehensive transportation for your entire wedding day, including bride, groom, and bridal party.',
                'duration_hours' => 6,
                'passenger_capacity' => 8,
                'luggage_capacity' => 4,
                'base_price' => 299.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 5,
                'min_booking_hours' => 6,
                'availability_24_7' => false,
                'inclusions' => ['Multiple chauffeurs', 'Fleet of luxury vehicles', 'Red carpet service', 'Champagne & refreshments', 'Vehicle decoration', 'Coordination with wedding planner', 'Unlimited photos'],
                'exclusions' => ['Venue coordination fees'],
                'quick_facts' => ['vehicle' => 'Luxury Fleet', 'availability' => 'By appointment'],
                'terms_conditions' => 'Minimum 1-month advance booking required for luxury package.',
                'cancellation_policy' => 'Free cancellation up to 30 days. 50% refund up to 14 days.',
                'meta_title' => 'Luxury Wedding Chauffeur Package',
                'meta_description' => 'Comprehensive wedding transportation with luxury fleet and professional service.',
            ],
            
            // Corporate Packages
            [
                'name' => 'Corporate Travel - Executive',
                'slug' => 'corporate-travel-executive',
                'category' => 'corporate',
                'short_description' => 'Professional business travel solutions',
                'description' => 'Professional business travel solutions for meetings, events, and corporate functions. Reliable, punctual, and discreet service.',
                'duration_hours' => 2,
                'passenger_capacity' => 4,
                'luggage_capacity' => 2,
                'base_price' => 59.00,
                'pricing_type' => 'hourly',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 6,
                'min_booking_hours' => 2,
                'availability_24_7' => true,
                'inclusions' => ['Professional chauffeur', 'Executive sedan', 'WiFi & charging ports', 'Newspapers & magazines', 'Bottled water', 'Invoice & receipt'],
                'exclusions' => ['Parking fees', 'Additional waiting time'],
                'quick_facts' => ['vehicle' => 'Executive Sedan', 'availability' => '24/7'],
                'terms_conditions' => 'Corporate account setup available. Minimum 2-hour booking.',
                'cancellation_policy' => 'Free cancellation up to 2 hours before scheduled time.',
                'meta_title' => 'Executive Corporate Travel Service',
                'meta_description' => 'Professional chauffeur service for business travel and corporate events.',
            ],
            [
                'name' => 'Corporate Conference Package',
                'slug' => 'corporate-conference-package',
                'category' => 'corporate',
                'short_description' => 'Full-day conference transportation',
                'description' => 'Comprehensive transportation solution for corporate conferences and multi-stop business itineraries.',
                'duration_hours' => 8,
                'passenger_capacity' => 6,
                'luggage_capacity' => 4,
                'base_price' => 399.00,
                'pricing_type' => 'daily',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 7,
                'min_booking_hours' => 8,
                'availability_24_7' => true,
                'inclusions' => ['Professional chauffeur', 'Luxury vehicle', 'WiFi & office setup', 'Refreshments', 'Multi-stop itinerary', 'Flexible scheduling', 'Corporate invoicing'],
                'exclusions' => ['Overnight parking', 'Interstate travel'],
                'quick_facts' => ['vehicle' => 'Luxury Executive Van', 'availability' => '24/7'],
                'terms_conditions' => 'Minimum 48-hour advance booking. Corporate rates available.',
                'cancellation_policy' => 'Free cancellation up to 24 hours before event.',
                'meta_title' => 'Corporate Conference Transportation',
                'meta_description' => 'Full-day chauffeur service for conferences and business events.',
            ],
            
            // City Tour Packages
            [
                'name' => 'City Tour - Half Day',
                'slug' => 'city-tour-half-day',
                'category' => 'city_tour',
                'short_description' => 'Explore the city with a private chauffeur',
                'description' => 'Discover the city\'s highlights with a private chauffeur and custom itinerary. Perfect for tourists and visitors.',
                'duration_hours' => 4,
                'passenger_capacity' => 3,
                'luggage_capacity' => 2,
                'base_price' => 119.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 8,
                'min_booking_hours' => 4,
                'availability_24_7' => false,
                'inclusions' => ['Professional chauffeur', 'Luxury vehicle', 'Custom itinerary', 'Photo stops', 'Bottled water', 'Local recommendations'],
                'exclusions' => ['Attraction entry fees', 'Meals', 'Tour guide'],
                'quick_facts' => ['vehicle' => 'Luxury Sedan', 'availability' => 'Daily 9AM-6PM'],
                'terms_conditions' => 'Minimum 24-hour advance booking. Custom itinerary planned with guest.',
                'cancellation_policy' => 'Free cancellation up to 24 hours before tour.',
                'meta_title' => 'Half Day City Tour with Private Chauffeur',
                'meta_description' => 'Explore the city highlights with private chauffeur service.',
            ],
            [
                'name' => 'City Tour - Full Day',
                'slug' => 'city-tour-full-day',
                'category' => 'city_tour',
                'short_description' => 'Comprehensive full-day city exploration',
                'description' => 'Full-day private city tour with flexible itinerary and comprehensive coverage of major attractions and hidden gems.',
                'duration_hours' => 8,
                'passenger_capacity' => 4,
                'luggage_capacity' => 2,
                'base_price' => 199.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 9,
                'min_booking_hours' => 8,
                'availability_24_7' => false,
                'inclusions' => ['Professional chauffeur', 'Luxury vehicle', 'Comprehensive itinerary', 'Multiple photo stops', 'Lunch stop included', 'Refreshments', 'Local insights'],
                'exclusions' => ['Attraction tickets', 'Meals', 'Professional tour guide'],
                'quick_facts' => ['vehicle' => 'Luxury SUV', 'availability' => 'Daily 8AM-8PM'],
                'terms_conditions' => 'Minimum 48-hour advance booking. Customizable itinerary.',
                'cancellation_policy' => 'Free cancellation up to 48 hours before tour.',
                'meta_title' => 'Full Day City Tour Package',
                'meta_description' => 'Comprehensive city exploration with private chauffeur and luxury vehicle.',
            ],
            
            // Group Packages
            [
                'name' => 'Group Events - Small',
                'slug' => 'group-events-small',
                'category' => 'group',
                'short_description' => 'Perfect for small group outings',
                'description' => 'Luxury transport for parties, concerts, and group outings. Comfortable and convenient transportation for your group.',
                'duration_hours' => 5,
                'passenger_capacity' => 10,
                'luggage_capacity' => 6,
                'base_price' => 149.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 10,
                'min_booking_hours' => 4,
                'availability_24_7' => true,
                'inclusions' => ['Professional chauffeur', 'Luxury passenger van', 'Sound system', 'Refreshments', 'Flexible pickup/dropoff', '24/7 availability'],
                'exclusions' => ['Alcohol service', 'Event tickets', 'Multiple distant locations'],
                'quick_facts' => ['vehicle' => 'Luxury Passenger Van', 'availability' => '24/7'],
                'terms_conditions' => 'Minimum 48-hour advance booking. Group deposit required.',
                'cancellation_policy' => 'Free cancellation up to 72 hours. 50% refund up to 24 hours.',
                'meta_title' => 'Small Group Event Transportation',
                'meta_description' => 'Luxury transportation for small group events and outings.',
            ],
            [
                'name' => 'Group Events - Large',
                'slug' => 'group-events-large',
                'category' => 'group',
                'short_description' => 'Premium transportation for large groups',
                'description' => 'Comprehensive transportation solution for large group events, corporate outings, and special occasions.',
                'duration_hours' => 8,
                'passenger_capacity' => 15,
                'luggage_capacity' => 10,
                'base_price' => 299.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 11,
                'min_booking_hours' => 6,
                'availability_24_7' => true,
                'inclusions' => ['Multiple professional chauffeurs', 'Fleet of vehicles', 'Coordination service', 'Sound system', 'Refreshment setup', 'Flexible scheduling', 'Group coordinator'],
                'exclusions' => ['Overnight service', 'Interstate travel', 'Event management'],
                'quick_facts' => ['vehicle' => 'Luxury Fleet', 'availability' => '24/7'],
                'terms_conditions' => 'Minimum 1-week advance booking. 50% deposit required.',
                'cancellation_policy' => 'Free cancellation up to 7 days. 50% refund up to 72 hours.',
                'meta_title' => 'Large Group Event Transportation',
                'meta_description' => 'Fleet service for large group events and corporate functions.',
            ],
            
            // Custom Packages
            [
                'name' => 'Custom Package - Flexible',
                'slug' => 'custom-package-flexible',
                'category' => 'custom',
                'short_description' => 'Tailored services for unique requirements',
                'description' => 'Completely customizable chauffeur service tailored to your specific needs and requirements. Contact us to discuss your unique transportation needs.',
                'duration_hours' => 0,
                'passenger_capacity' => 0,
                'luggage_capacity' => 0,
                'base_price' => 0.00,
                'pricing_type' => 'fixed',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 12,
                'min_booking_hours' => null,
                'availability_24_7' => true,
                'inclusions' => ['Fully customizable service', 'Professional consultation', 'Tailored vehicle selection', 'Custom itinerary', 'Dedicated coordinator', 'Premium service'],
                'exclusions' => ['Pricing varies based on requirements'],
                'quick_facts' => ['vehicle' => 'Based on Requirements', 'availability' => 'By Arrangement'],
                'terms_conditions' => 'Contact for custom quote. Minimum booking terms vary by service.',
                'cancellation_policy' => 'Cancellation policy determined based on custom requirements.',
                'meta_title' => 'Custom Chauffeur Service Package',
                'meta_description' => 'Completely customizable chauffeur service for your unique needs.',
            ],
        ];

        foreach ($packages as $packageData) {
            Package::create($packageData);
        }
    }
}
